suivi_projet_developper_cra:
    pattern:  /compte_rendu_dactivite
    defaults: { _controller: suiviProjetDevelopperBundle:Developper:afficheCraVue }
    
suivi_projet_developper_cra_individuel:
    pattern:  /compte_rendu_dactivite_individuel
    defaults: { _controller: suiviProjetDevelopperBundle:Developper:afficheCraIndividuelVue }
