sprint_tableau_de_bord_sprint:
    pattern:  /tableau_de_bord_sprint
    defaults: { _controller: SprintBundle:Sprint:afficheTableauDeBordSprintVue }
    
sprint_ajout_equipe:
    pattern:  /ajout_equipe
    defaults: { _controller: SprintBundle:Sprint:ajoutEquipeVue }