parameters:
#    sprint.example.class: Suiviprojet\SprintBundle\Example

services:
#    sprint.example:
#        class: %sprint.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
