<?php

namespace Suiviprojet\BlacklogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlacklogProductController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Suiviprojet\BlacklogBundle\Controller\BlacklogProductController();
        return $instance;
    }
}
