<?php

namespace Suiviprojet\ClientBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FacturationDevisController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Suiviprojet\ClientBundle\Controller\FacturationDevisController();
        return $instance;
    }
}
