<?php

namespace Suiviprojet\AdministrateurBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdministrateurController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Suiviprojet\AdministrateurBundle\Controller\AdministrateurController();
        return $instance;
    }
}
