<?php

namespace suiviProjet\DevelopperBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DevelopperController__JMSInjector
{
    public static function inject($container) {
        $instance = new \suiviProjet\DevelopperBundle\Controller\DevelopperController();
        return $instance;
    }
}
