<?php

namespace Suiviprojet\SprintBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SprintController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Suiviprojet\SprintBundle\Controller\SprintController();
        return $instance;
    }
}
