suiviprojet_administrateur_creation_projet:
    pattern:  /creation_projet
    defaults: { _controller: SuiviprojetAdministrateurBundle:Administrateur:creationProjet }
    
suiviprojet_administrateur_creation_compte_client:
    pattern:  /creation_compte_client
    defaults: { _controller: SuiviprojetAdministrateurBundle:Administrateur:creationCompteClient }
    


