parameters:
#    suiviprojet_administrateur.example.class: Suiviprojet\AdministrateurBundle\Example

services:
#    suiviprojet_administrateur.example:
#        class: %suiviprojet_administrateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
